### PR TITLE
fixed link tag

### PR DESCRIPTION
**Pull request by jkreft-usgs**
fixed a tag to make 508 compliance checker happy- more changes on the way

### CODE REVIEW

**Comment by jread-usgs** [comment]
:+1:

**Comment by jread-usgs** [comment]
@jkreft-usgs you going to keep adding to this PR or do you want to merge it now?

**Comment by jiwalker-usgs** [comment]
The changes here actually need to be made in the src_data/html/*.mustache files.  The html in public_html is all generated from there.

**Comment by jiwalker-usgs** [comment]
And a note for future self (you can ignore this comment @jkreft-usgs) we should probably put alt text in the translation file and template it in so we can have alt text in the correct language.

**Comment by jread-usgs** [comment]
whoops, forgot the `'stache`

**Comment by jkreft-usgs** [comment]
nope, I'm out at this point until sometime next week.  I sent an email that covers what you need to do to make the other errors (titles on the input tags) go away.

**Comment by jiwalker-usgs** [comment]
Thanks Jim, I'll run with the changes in the email.  I'm going to close this PR and get the above changes into the mustache files.  Thanks for getting the ball rolling with this.

**Pull request closed without merging**
